name: Test on PR

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DB
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22.x'
        - name: create env file
          run: |
            touch .env.test
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env.test
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env.test
            echo DB_USER=${{ secrets.DB_USER }} >> .env.test
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env.test
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env.test
            echo CLOUD_NAME=${{ secrets.CLOUD_NAME }} >> .env.test
            echo API_KEY=${{ secrets.API_KEY }} >> .env.test
            echo API_SECRET=${{ secrets.API_SECRET }} >> .env.test
        - run: npm ci
        - run: npm run lint
        - run: npm test
        - run: npm run build --if-present
